### ISSUE TITLE
Practica en figma y reporte 1 

### ISSUE THREAD

**Issue by RicardoMtzSts** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-topicos-a-grupo-us#3]
[REPORTE 1 FIGMA MOCKUP.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-topicos-a-grupo-us/files/10779959/REPORTE.1.FIGMA.MOCKUP.pdf)

https://www.figma.com/proto/BBTL4KiY8bCSQ6fH54Usvc/Untitled?node-id=97%3A208&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=97%3A208

**Comment by Nelsy21** [comment]
De acuerdo al análisis y la revisión del trabajo podemos deducir que el equipo obtuvo el 15.6 del total tomando en cuenta los criterios de la rubrica.                                                                                                                                                                                  
Portada: 17, Usen un solo formato en la portada.
imágenes: 17, Ocupar mas capturas de pantalla, para explicar detalladamente el desarrollo de la practica. 
Procedimiento: 22, sean mas específicos en los detalles de la redacción, procurando darle un mismo formato a todo el reporte.
resultado y conclusión: 17, deben ser mas explícitos. 
total=78 puntos   calificación=15.6

**Comment by Nelsy21** [comment]
De acuerdo al análisis y la revisión del trabajo podemos deducir que el equipo obtuvo el 15.6 del total tomando en cuenta los criterios de la rubrica.
Buen diseño de Mockup.
Portada: 22, Usen un solo formato en la portada.
imágenes: 22, Ocupar mas capturas de pantalla, para explicar detalladamente el desarrollo de la practica.
Procedimiento: 17, sean mas específicos en los detalles de la redacción, procurando darle un mismo formato a todo el reporte.
resultado y conclusión: 17, deben ser mas explícitos.
total=78 puntos calificación=15.6

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
